from django.core.management.base import BaseCommand
from biblioteca.models import *

codigos = [

# ================================================================================================================ #
#                                                       HTML                                                       #
# ================================================================================================================ #

    # --- Raiz e Metadados ---

    ('html', 'Elemento raiz de todo documento HTML.', '<html></html>', 'Raiz e Metadados', 'html'),
    ('head', 'Contém metadados e configurações do documento.', '<head></head>', 'Raiz e Metadados', 'html'),
    ('body', 'Contém todo o conteúdo visível da página.', '<body></body>', 'Raiz e Metadados', 'html'),
    ('title', 'Define o título da página exibido na aba do navegador.', '<title>Minha Página</title>', 'Raiz e Metadados', 'html'),
    ('meta', 'Define metadados como charset, descrição e viewport.', '<meta charset="UTF-8">', 'Raiz e Metadados', 'html'),
    ('meta viewport', 'Define configurações de responsividade.', '<meta name="viewport" content="width=device-width, initial-scale=1.0">', 'Raiz e Metadados', 'html'),
    ('meta description', 'Define descrição da página para SEO.', '<meta name="description" content="Descrição do site">', 'Raiz e Metadados', 'html'),
    ('link', 'Relaciona arquivos externos como CSS ou favicon.', '<link rel="stylesheet" href="style.css">', 'Raiz e Metadados', 'html'),
    ('link favicon', 'Define o ícone da aba do navegador.', '<link rel="icon" href="favicon.ico">', 'Raiz e Metadados', 'html'),
    ('style','A tag <style> é usada para incorporar CSS diretamente no documento HTML.','<style> CSS aqui </style>', 'Raiz e Metadados', 'html'),
    ('script', 'Importa ou executa scripts JavaScript.', '<script src="script.js"></script>', 'Raiz e Metadados', 'html'),
    ('script defer', 'Carrega o script após o HTML ser processado.', '<script src="script.js" defer></script>', 'Raiz e Metadados', 'html'),
    ('base', 'Define URL base para links relativos.', '<base href="https://exemplo.com/">', 'Raiz e Metadados', 'html'),
    ('noscript', 'Define conteúdo exibido quando JavaScript está desativado.', '<noscript>Ative o JavaScript</noscript>', 'Raiz e Metadados', 'html'),

    # --- Texto e Títulos ---

    ('h1', 'Define o título mais importante da página.', '<h1>Título</h1>', 'Texto e Títulos', 'html'),
    ('h2', 'Define um subtítulo de nível 2.', '<h2>Subtítulo</h2>', 'Texto e Títulos', 'html'),
    ('h3', 'Define um subtítulo de nível 3.', '<h3>Subtítulo</h3>', 'Texto e Títulos', 'html'),
    ('h4', 'Define um subtítulo de nível 4.', '<h4>Subtítulo</h4>', 'Texto e Títulos', 'html'),
    ('h5', 'Define um subtítulo de nível 5.', '<h5>Subtítulo</h5>', 'Texto e Títulos', 'html'),
    ('h6', 'Define um subtítulo de nível 6.', '<h6>Subtítulo</h6>', 'Texto e Títulos', 'html'),
    ('p', 'Define um parágrafo de texto.', '<p>Parágrafo</p>', 'Texto e Títulos', 'html'),
    ('br', 'Insere uma quebra de linha.', 'Texto<br>Nova linha', 'Texto e Títulos', 'html'),
    ('hr', 'Insere uma linha horizontal temática.', '<hr>', 'Texto e Títulos', 'html'),
    ('strong', 'Indica importância semântica (negrito).', '<strong>Importante</strong>', 'Texto e Títulos', 'html'),
    ('em', 'Indica ênfase semântica (itálico).', '<em>Ênfase</em>', 'Texto e Títulos', 'html'),
    ('b', 'Aplica negrito sem valor semântico.', '<b>Negrito</b>', 'Texto e Títulos', 'html'),
    ('i', 'Aplica itálico sem valor semântico.', '<i>Itálico</i>', 'Texto e Títulos', 'html'),
    ('u', 'Sublinha o texto.', '<u>Sublinhado</u>', 'Texto e Títulos', 'html'),
    ('small', 'Define texto menor.', '<small>Texto pequeno</small>', 'Texto e Títulos', 'html'),
    ('mark', 'Destaca texto como marcado.', '<mark>Texto destacado</mark>', 'Texto e Títulos', 'html'),
    ('del', 'Define texto removido.', '<del>Texto removido</del>', 'Texto e Títulos', 'html'),
    ('ins', 'Define texto inserido.', '<ins>Texto inserido</ins>', 'Texto e Títulos', 'html'),
    ('sub', 'Define texto subscrito.', 'H<sub>2</sub>O', 'Texto e Títulos', 'html'),
    ('sup', 'Define texto sobrescrito.', '2<sup>10</sup>', 'Texto e Títulos', 'html'),
    ('blockquote', 'Define uma citação em bloco.', '<blockquote>Citação longa</blockquote>', 'Texto e Títulos', 'html'),
    ('q', 'Define uma citação curta.', '<q>Citação curta</q>', 'Texto e Títulos', 'html'),
    ('cite', 'Define o título de uma obra.', '<cite>Nome do Livro</cite>', 'Texto e Títulos', 'html'),
    ('abbr', 'Define uma abreviação.', '<abbr title="HyperText Markup Language">HTML</abbr>', 'Texto e Títulos', 'html'),
    ('address', 'Define informações de contato.', '<address>email@site.com</address>', 'Texto e Títulos', 'html'),
    ('pre', 'Define texto pré-formatado.', '<pre>Texto    formatado</pre>', 'Texto e Títulos', 'html'),
    ('code', 'Define um trecho de código.', '<code>console.log("Hello")</code>', 'Texto e Títulos', 'html'),

    # --- Estruturação de Conteúdo (Semânticas)---

("div","Elemento genérico de divisão sem significado semântico.",'<div> Parte da página aqui </div>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("section","Define uma seção temática do documento.",'<section> Sessão da página aqui </section>','Estruturação de Conteúdo (Semânticas)', 'html'),
("article","Representa conteúdo independente e reutilizável.",'<article> Conteudo independente aqui </article>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("header","Define o cabeçalho de uma página ou seção.",'<header> Conteudo do cabeçalho da página </header>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("footer","Define o rodapé de uma página ou seção.",'<footer> conteudos finais da página aqui </footer>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("main","Define o conteúdo principal do documento.",'<main> Conteúdo principal da página </main>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("nav","Define uma área de navegação.",'<nav> <a href="#">Home</a> <a href="#">Sobre</a> </nav>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("aside","Define conteúdo complementar.",'<aside> Conteúdo lateral ou complementar </aside>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("figure","Agrupa conteúdo ilustrativo.",'<figure> <img src="imagem.jpg" alt="Descrição"> </figure>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("figcaption","Define a legenda de um figure.",'<figure> <img src="img.jpg"> <figcaption>Legenda da imagem</figcaption> </figure>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("address","Representa informações de contato.",'<address> contato@email.com </address>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("details","Cria um bloco expansível.",'<details> Conteúdo oculto </details>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("summary","Define o título do details.",'<details> <summary>Título</summary> Conteúdo aqui </details>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("dialog","Define uma caixa de diálogo ou modal.",'<dialog open> Conteúdo do modal </dialog>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("template","Define conteúdo HTML não renderizado.",'<template id="modelo"> <p>Conteúdo oculto</p> </template>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("slot","Define um ponto de inserção em Web Components.",'<slot> Conteúdo padrão </slot>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("fieldset","Agrupa campos relacionados em formulários.",'<fieldset> <input type="text"> </fieldset>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("legend","Define o título de um fieldset.",'<fieldset> <legend>Informações</legend> </fieldset>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("datalist","Fornece sugestões para inputs.",'<input list="opcoes"> <datalist id="opcoes"> <option value="HTML"> </datalist>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("menu","Define uma lista de comandos.",'<menu> <li>Item 1</li> <li>Item 2</li> </menu>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("menuitem","Define um item de menu.",'<menu> <menuitem label="Salvar"></menuitem> </menu>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("output","Exibe o resultado de um cálculo.",'<output>Resultado aqui</output>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("progress","Representa o progresso de uma tarefa.",'<progress value="50" max="100"></progress>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("meter","Representa uma medida dentro de um intervalo.",'<meter value="6" min="0" max="10"></meter>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("search","Representa uma seção de busca.",'<search> <input type="search" placeholder="Pesquisar"> </search>', 'Estruturação de Conteúdo (Semânticas)', 'html'),
("content","Elemento antigo do Shadow DOM.",'<content></content>', 'Estruturação de Conteúdo (Semânticas)', 'html'),

# ================================================================================================================ #
#                                                       CSS                                                        #
# ================================================================================================================ #

    # --- Texto e Tipografia ---

    ("font","Shorthand para definir várias propriedades da fonte de uma vez.","font: italic bold 16px Arial, sans-serif;","Texto e Tipografia","css"),
    ("font-family","Define a família da fonte do texto.","font-family: 'Arial', sans-serif;","Texto e Tipografia","css"),
    ("font-style","Define o estilo da fonte (normal, italic, oblique).","font-style: italic;","Texto e Tipografia","css"),
    ("font-weight","Define a espessura da fonte.","font-weight: 700;","Texto e Tipografia","css"),
    ("font-stretch","Controla a largura da fonte.","font-stretch: expanded;","Texto e Tipografia","css"),
    ("font-size","Define o tamanho da fonte.","font-size: 18px;","Texto e Tipografia","css"),
    ("font-size-adjust","Ajusta o tamanho da fonte baseado na altura-x.","font-size-adjust: 0.5;","Texto e Tipografia","css"),
    ("font-kerning","Controla o ajuste de espaço entre pares de letras.","font-kerning: normal;","Texto e Tipografia","css"),
    ("font-variant","Shorthand para variantes tipográficas.","font-variant: small-caps;","Texto e Tipografia","css"),
    ("font-variant-caps","Controla variações de letras maiúsculas.","font-variant-caps: small-caps;","Texto e Tipografia","css"),
    ("font-variant-ligatures","Controla ligaduras tipográficas.","font-variant-ligatures: none;","Texto e Tipografia","css"),
    ("font-variant-numeric","Controla variações numéricas.","font-variant-numeric: lining-nums;","Texto e Tipografia","css"),
    ("font-variant-east-asian","Controla variantes para idiomas asiáticos.","font-variant-east-asian: ruby;","Texto e Tipografia","css"),
    ("font-variant-alternates","Controla glifos alternativos.","font-variant-alternates: historical-forms;","Texto e Tipografia","css"),
    ("font-variant-position","Controla posição tipográfica (sub/super).","font-variant-position: super;","Texto e Tipografia","css"),
    ("font-feature-settings","Permite ativar recursos OpenType.","font-feature-settings: 'liga' 0;","Texto e Tipografia","css"),
    ("font-variation-settings","Controla eixos de fontes variáveis.","font-variation-settings: 'wght' 700;","Texto e Tipografia","css"),
    ("font-optical-sizing","Controla ajuste óptico automático.","font-optical-sizing: auto;","Texto e Tipografia","css"),
    ("font-palette","Seleciona paleta de cores em fontes coloridas.","font-palette: dark;","Texto e Tipografia","css"),
    ("font-synthesis","Controla síntese automática de estilos.","font-synthesis: none;","Texto e Tipografia","css"),
    ("font-synthesis-weight","Controla síntese de peso da fonte.","font-synthesis-weight: none;","Texto e Tipografia","css"),
    ("font-synthesis-style","Controla síntese de estilo.","font-synthesis-style: none;","Texto e Tipografia","css"),
    ("font-synthesis-small-caps","Controla síntese de small-caps.","font-synthesis-small-caps: none;","Texto e Tipografia","css"),
    ("line-height","Define a altura da linha do texto.","line-height: 1.6;","Texto e Tipografia","css"),
    ("letter-spacing","Define o espaçamento entre letras.","letter-spacing: 2px;","Texto e Tipografia","css"),
    ("word-spacing","Define o espaçamento entre palavras.","word-spacing: 4px;","Texto e Tipografia","css"),
    ("text-indent","Define recuo da primeira linha.","text-indent: 20px;","Texto e Tipografia","css"),
    ("tab-size","Define o tamanho do caractere TAB.","tab-size: 4;","Texto e Tipografia","css"),
    ("text-align","Define o alinhamento horizontal do texto.","text-align: center;","Texto e Tipografia","css"),
    ("text-align-last","Define alinhamento da última linha.","text-align-last: right;","Texto e Tipografia","css"),
    ("text-justify","Controla método de justificação.","text-justify: inter-word;","Texto e Tipografia","css"),
    ("vertical-align","Alinha elementos inline verticalmente.","vertical-align: middle;","Texto e Tipografia","css"),
    ("text-decoration","Shorthand para decoração do texto.","text-decoration: underline;","Texto e Tipografia","css"),
    ("text-decoration-line","Define tipo de linha decorativa.","text-decoration-line: underline;","Texto e Tipografia","css"),
    ("text-decoration-style","Define estilo da linha decorativa.","text-decoration-style: dashed;","Texto e Tipografia","css"),
    ("text-decoration-color","Define cor da decoração.","text-decoration-color: red;","Texto e Tipografia","css"),
    ("text-decoration-thickness","Define espessura da decoração.","text-decoration-thickness: 2px;","Texto e Tipografia","css"),
    ("text-underline-offset","Define distância do sublinhado.","text-underline-offset: 3px;","Texto e Tipografia","css"),
    ("text-underline-position","Define posição do sublinhado.","text-underline-position: under;","Texto e Tipografia","css"),
    ("text-shadow","Adiciona sombra ao texto.","text-shadow: 2px 2px 4px black;","Texto e Tipografia","css"),
    ("text-transform","Controla capitalização do texto.","text-transform: uppercase;","Texto e Tipografia","css"),
    ("white-space","Controla como espaços e quebras são tratados.","white-space: nowrap;","Texto e Tipografia","css"),
    ("overflow-wrap","Permite quebra de palavras longas.","overflow-wrap: break-word;","Texto e Tipografia","css"),
    ("word-break","Define como palavras podem quebrar.","word-break: break-all;","Texto e Tipografia","css"),
    ("line-break","Controla quebra de linha em idiomas asiáticos.","line-break: strict;","Texto e Tipografia","css"),
    ("hyphens","Controla hifenização automática.","hyphens: auto;","Texto e Tipografia","css"),
    ("text-overflow","Define comportamento de overflow no texto.","text-overflow: ellipsis;","Texto e Tipografia","css"),
    ("direction","Define direção do texto (ltr/rtl).","direction: rtl;","Texto e Tipografia","css"),
    ("unicode-bidi","Controla comportamento bidirecional.","unicode-bidi: bidi-override;","Texto e Tipografia","css"),
    ("writing-mode","Define modo de escrita vertical/horizontal.","writing-mode: vertical-rl;","Texto e Tipografia","css"),
    ("text-orientation","Controla orientação em escrita vertical.","text-orientation: upright;","Texto e Tipografia","css"),
    ("text-wrap","Controla como o texto deve quebrar linhas.","text-wrap: balance;","Texto e Tipografia","css"),
    ("white-space-collapse","Controla como espaços em branco são tratados.","white-space-collapse: collapse;","Texto e Tipografia","css"),
    ("text-emphasis","Shorthand para adicionar marcas de ênfase em textos (usado em idiomas asiáticos).","text-emphasis: dot red;","Texto e Tipografia","css"),
    ("text-emphasis-style","Define o estilo da marca de ênfase.","text-emphasis-style: circle;","Texto e Tipografia","css"),
    ("text-emphasis-color","Define a cor da marca de ênfase.","text-emphasis-color: red;","Texto e Tipografia","css"),
    ("text-emphasis-position","Define a posição da marca de ênfase.","text-emphasis-position: over right;","Texto e Tipografia","css"),
    ("text-combine-upright","Combina caracteres em escrita vertical.","text-combine-upright: all;","Texto e Tipografia","css"),
    ("text-rendering","Controla a otimização de renderização do texto.","text-rendering: optimizeLegibility;","Texto e Tipografia","css"),
    ("font-smooth","Controla suavização da fonte (não padrão).","font-smooth: always;","Texto e Tipografia","css"),
    ("-webkit-font-smoothing","Controla suavização da fonte no WebKit.","-webkit-font-smoothing: antialiased;","Texto e Tipografia","css"),
    ("-moz-osx-font-smoothing","Controla suavização da fonte no macOS.","-moz-osx-font-smoothing: grayscale;","Texto e Tipografia","css"),
    ("leading-trim","Remove espaço extra acima/abaixo do texto.","leading-trim: both;","Texto e Tipografia","css"),
    ("text-edge","Controla alinhamento visual baseado nas bordas tipográficas.","text-edge: cap;","Texto e Tipografia","css"),
    ("initial-letter","Define tamanho inicial estilizada (drop cap).","initial-letter: 2;","Texto e Tipografia","css"),
    ("initial-letter-align","Define alinhamento da letra inicial estilizada.","initial-letter-align: alphabetic;","Texto e Tipografia","css"),
    ("font-language-override","Força uso de regras tipográficas de outro idioma.","font-language-override: 'TRK';","Texto e Tipografia","css"),
    ("color","Define a cor do texto.","color: #333;","Texto e Tipografia","css"),
    ("caret-color","Define a cor do cursor de texto.","caret-color: red;","Texto e Tipografia","css"),
    ("quotes","Define o estilo de aspas usadas no elemento.","quotes: '«' '»';","Texto e Tipografia","css"),
    ('font-feature-settings', 'Controla recursos tipográficos OpenType como ligaduras.', 'p { font-feature-settings: "liga" 1; }', 'Texto e Tipografia', 'css'),
    ('font-kerning', 'Ativa ou desativa kerning automático entre caracteres.', 'p { font-kerning: normal; }', 'Texto e Tipografia', 'css'),
    ('font-stretch', 'Alonga ou comprime a largura da fonte.', 'p { font-stretch: condensed; }', 'Texto e Tipografia', 'css'),
    ('hyphens', 'Controla a hifenização automática do texto.', 'p { hyphens: auto; }', 'Texto e Tipografia', 'css'),

    # Box Model

    ("width","Define a largura do elemento.","width: 200px;","Box Model","css"),
    ("min-width","Define a largura mínima do elemento.","min-width: 150px;","Box Model","css"),
    ("max-width","Define a largura máxima do elemento.","max-width: 500px;","Box Model","css"),
    ("height","Define a altura do elemento.","height: 300px;","Box Model","css"),
    ("min-height","Define a altura mínima do elemento.","min-height: 100px;","Box Model","css"),
    ("max-height","Define a altura máxima do elemento.","max-height: 600px;","Box Model","css"),
    ("margin","Shorthand para definir margens externas.","margin: 10px 20px;","Box Model","css"),
    ("margin-top","Define margem superior.","margin-top: 10px;","Box Model","css"),
    ("margin-right","Define margem direita.","margin-right: 20px;","Box Model","css"),
    ("margin-bottom","Define margem inferior.","margin-bottom: 10px;","Box Model","css"),
    ("margin-left","Define margem esquerda.","margin-left: 20px;","Box Model","css"),
    ("padding","Shorthand para definir espaçamento interno.","padding: 15px;","Box Model","css"),
    ("padding-top","Define padding superior.","padding-top: 10px;","Box Model","css"),
    ("padding-right","Define padding direito.","padding-right: 15px;","Box Model","css"),
    ("padding-bottom","Define padding inferior.","padding-bottom: 10px;","Box Model","css"),
    ("padding-left","Define padding esquerdo.","padding-left: 15px;","Box Model","css"),
    ("border","Shorthand para definir borda.","border: 1px solid black;","Box Model","css"),
    ("border-width","Define espessura da borda.","border-width: 2px;","Box Model","css"),
    ("border-style","Define estilo da borda.","border-style: dashed;","Box Model","css"),
    ("border-color","Define cor da borda.","border-color: red;","Box Model","css"),
    ("border-top","Define borda superior.","border-top: 1px solid black;","Box Model","css"),
    ("border-right","Define borda direita.","border-right: 1px solid black;","Box Model","css"),
    ("border-bottom","Define borda inferior.","border-bottom: 1px solid black;","Box Model","css"),
    ("border-left","Define borda esquerda.","border-left: 1px solid black;","Box Model","css"),
    ("border-top-width","Define largura da borda superior.","border-top-width: 2px;","Box Model","css"),
    ("border-right-width","Define largura da borda direita.","border-right-width: 2px;","Box Model","css"),
    ("border-bottom-width","Define largura da borda inferior.","border-bottom-width: 2px;","Box Model","css"),
    ("border-left-width","Define largura da borda esquerda.","border-left-width: 2px;","Box Model","css"),
    ("border-top-style","Define estilo da borda superior.","border-top-style: solid;","Box Model","css"),
    ("border-right-style","Define estilo da borda direita.","border-right-style: solid;","Box Model","css"),
    ("border-bottom-style","Define estilo da borda inferior.","border-bottom-style: solid;","Box Model","css"),
    ("border-left-style","Define estilo da borda esquerda.","border-left-style: solid;","Box Model","css"),
    ("border-top-color","Define cor da borda superior.","border-top-color: red;","Box Model","css"),
    ("border-right-color","Define cor da borda direita.","border-right-color: red;","Box Model","css"),
    ("border-bottom-color","Define cor da borda inferior.","border-bottom-color: red;","Box Model","css"),
    ("border-left-color","Define cor da borda esquerda.","border-left-color: red;","Box Model","css"),
    ("border-radius","Define arredondamento das bordas.","border-radius: 10px;","Box Model","css"),
    ("border-top-left-radius","Define arredondamento do canto superior esquerdo.","border-top-left-radius: 10px;","Box Model","css"),
    ("border-top-right-radius","Define arredondamento do canto superior direito.","border-top-right-radius: 10px;","Box Model","css"),
    ("border-bottom-right-radius","Define arredondamento do canto inferior direito.","border-bottom-right-radius: 10px;","Box Model","css"),
    ("border-bottom-left-radius","Define arredondamento do canto inferior esquerdo.","border-bottom-left-radius: 10px;","Box Model","css"),
    ("box-sizing","Define como largura e altura são calculadas.","box-sizing: border-box;","Box Model","css"),
    ("box-shadow","Adiciona sombra ao elemento.","box-shadow: 2px 2px 8px rgba(0,0,0,0.3);","Box Model","css"),
    ("outline","Shorthand para contorno externo.","outline: 2px solid blue;","Box Model","css"),
    ("outline-width","Define largura do contorno.","outline-width: 2px;","Box Model","css"),
    ("outline-style","Define estilo do contorno.","outline-style: solid;","Box Model","css"),
    ("outline-color","Define cor do contorno.","outline-color: blue;","Box Model","css"),
    ("outline-offset","Define distância do contorno ao elemento.","outline-offset: 4px;","Box Model","css"),
    ("overflow","Controla como conteúdo excedente é tratado.","overflow: hidden;","Box Model","css"),
    ("overflow-x","Controla overflow horizontal.","overflow-x: auto;","Box Model","css"),
    ("overflow-y","Controla overflow vertical.","overflow-y: scroll;","Box Model","css"),
    ("aspect-ratio","Define proporção fixa entre largura e altura.","aspect-ratio: 16 / 9;","Box Model","css"),
    ("resize","Permite redimensionar elemento.","resize: both;","Box Model","css"),
    ("overflow-clip-margin","Define margem extra para área de clipping.","overflow-clip-margin: 10px;","Box Model","css"),
    ("margin-block","Define margem no eixo de bloco.","margin-block: 10px;","Box Model","css"),
    ("margin-block-start","Define margem inicial no eixo de bloco.","margin-block-start: 10px;","Box Model","css"),
    ("margin-block-end","Define margem final no eixo de bloco.","margin-block-end: 10px;","Box Model","css"),
    ("margin-inline","Define margem no eixo inline.","margin-inline: 20px;","Box Model","css"),
    ("margin-inline-start","Define margem inicial inline.","margin-inline-start: 20px;","Box Model","css"),
    ("margin-inline-end","Define margem final inline.","margin-inline-end: 20px;","Box Model","css"),
    ("padding-block","Define padding no eixo de bloco.","padding-block: 15px;","Box Model","css"),
    ("padding-block-start","Define padding inicial no eixo de bloco.","padding-block-start: 15px;","Box Model","css"),
    ("padding-block-end","Define padding final no eixo de bloco.","padding-block-end: 15px;","Box Model","css"),
    ("padding-inline","Define padding no eixo inline.","padding-inline: 15px;","Box Model","css"),
    ("padding-inline-start","Define padding inicial inline.","padding-inline-start: 15px;","Box Model","css"),
    ("padding-inline-end","Define padding final inline.","padding-inline-end: 15px;","Box Model","css"),
    ("border-block","Define borda no eixo de bloco.","border-block: 1px solid black;","Box Model","css"),
    ("border-block-start","Define borda inicial no eixo de bloco.","border-block-start: 1px solid black;","Box Model","css"),
    ("border-block-end","Define borda final no eixo de bloco.","border-block-end: 1px solid black;","Box Model","css"),
    ("border-inline","Define borda no eixo inline.","border-inline: 1px solid black;","Box Model","css"),
    ("border-inline-start","Define borda inicial inline.","border-inline-start: 1px solid black;","Box Model","css"),
    ("border-inline-end","Define borda final inline.","border-inline-end: 1px solid black;","Box Model","css"),
    ("border-start-start-radius","Define raio lógico no canto inicial.","border-start-start-radius: 10px;","Box Model","css"),
    ("border-start-end-radius","Define raio lógico no canto inicial/final.","border-start-end-radius: 10px;","Box Model","css"),
    ("border-end-start-radius","Define raio lógico no canto final/inicial.","border-end-start-radius: 10px;","Box Model","css"),
    ("border-end-end-radius","Define raio lógico no canto final.","border-end-end-radius: 10px;","Box Model","css"),
    ("contain","Define isolamento de layout/pintura.","contain: layout;","Box Model","css"),
    ("contain-intrinsic-size","Define tamanho intrínseco para elementos contidos.","contain-intrinsic-size: 300px;","Box Model","css"),
    ("contain-intrinsic-width","Define largura intrínseca contida.","contain-intrinsic-width: 300px;","Box Model","css"),
    ("contain-intrinsic-height","Define altura intrínseca contida.","contain-intrinsic-height: 200px;","Box Model","css"),

    # --- Layout e posicionamento ---

    ("display","Define o tipo de exibição do elemento.","display: block;","Layout e Posicionamento","css"),
    ("visibility","Controla visibilidade do elemento.","visibility: hidden;","Layout e Posicionamento","css"),
    ("position","Define o tipo de posicionamento.","position: relative;","Layout e Posicionamento","css"),
    ("top","Define deslocamento superior para elementos posicionados.","top: 10px;","Layout e Posicionamento","css"),
    ("right","Define deslocamento direito para elementos posicionados.","right: 10px;","Layout e Posicionamento","css"),
    ("bottom","Define deslocamento inferior para elementos posicionados.","bottom: 10px;","Layout e Posicionamento","css"),
    ("left","Define deslocamento esquerdo para elementos posicionados.","left: 10px;","Layout e Posicionamento","css"),
    ("inset","Shorthand para top, right, bottom e left.","inset: 10px;","Layout e Posicionamento","css"),
    ("z-index","Define ordem de empilhamento dos elementos.","z-index: 5;","Layout e Posicionamento","css"),
    ("float","Define posicionamento flutuante.","float: left;","Layout e Posicionamento","css"),
    ("clear","Controla comportamento em relação a elementos flutuantes.","clear: both;","Layout e Posicionamento","css"),
    ("isolation","Define se o elemento cria novo contexto de empilhamento.","isolation: isolate;","Layout e Posicionamento","css"),
    ("inset-block","Define deslocamento no eixo de bloco.","inset-block: 10px;","Layout e Posicionamento","css"),
    ("inset-block-start","Define deslocamento inicial no eixo de bloco.","inset-block-start: 10px;","Layout e Posicionamento","css"),
    ("inset-block-end","Define deslocamento final no eixo de bloco.","inset-block-end: 10px;","Layout e Posicionamento","css"),
    ("inset-inline","Define deslocamento no eixo inline.","inset-inline: 10px;","Layout e Posicionamento","css"),
    ("inset-inline-start","Define deslocamento inicial inline.","inset-inline-start: 10px;","Layout e Posicionamento","css"),
    ("inset-inline-end","Define deslocamento final inline.","inset-inline-end: 10px;","Layout e Posicionamento","css"),
    ("overflow","Controla como conteúdo excedente é tratado.","overflow: hidden;","Layout e Posicionamento","css"),
    ("overflow-x","Controla overflow horizontal.","overflow-x: auto;","Layout e Posicionamento","css"),
    ("overflow-y","Controla overflow vertical.","overflow-y: scroll;","Layout e Posicionamento","css"),
    ("overflow-clip-margin","Define margem extra para área de clipping.","overflow-clip-margin: 10px;","Layout e Posicionamento","css"),
    ("clip","Define recorte de elemento posicionado (obsoleto).","clip: rect(0,50px,50px,0);","Layout e Posicionamento","css"),
    ("clip-path","Define recorte moderno do elemento.","clip-path: circle(50%);","Layout e Posicionamento","css"),
    ("will-change","Indica propriedades que irão mudar.","will-change: transform;","Layout e Posicionamento","css"),
    ("contain","Define isolamento de layout/pintura.","contain: layout;","Layout e Posicionamento","css"),
    ("content-visibility","Controla renderização baseada na visibilidade.","content-visibility: auto;","Layout e Posicionamento","css"),

    # --- Cores e Background ---

    ("color","Define a cor do texto.","color: #333;","Cores e Background","css"),
    ("opacity","Define o nível de transparência do elemento.","opacity: 0.5;","Cores e Background","css"),
    ("accent-color","Define cor de destaque para elementos de formulário.","accent-color: blue;","Cores e Background","css"),
    ("caret-color","Define a cor do cursor de texto.","caret-color: red;","Cores e Background","css"),
    ("color-scheme","Indica suporte a temas claro/escuro.","color-scheme: dark;","Cores e Background","css"),
    ("background","Shorthand para propriedades de fundo.","background: #000 url(img.png) no-repeat center/cover;","Cores e Background","css"),
    ("background-color","Define a cor de fundo.","background-color: #000;","Cores e Background","css"),
    ("background-image","Define imagem de fundo.","background-image: url('img.png');","Cores e Background","css"),
    ("background-position","Define posição da imagem de fundo.","background-position: center;","Cores e Background","css"),
    ("background-size","Define tamanho da imagem de fundo.","background-size: cover;","Cores e Background","css"),
    ("background-repeat","Define repetição da imagem de fundo.","background-repeat: no-repeat;","Cores e Background","css"),
    ("background-attachment","Define se fundo é fixo ou rola com a página.","background-attachment: fixed;","Cores e Background","css"),
    ("background-origin","Define origem do posicionamento do fundo.","background-origin: padding-box;","Cores e Background","css"),
    ("background-clip","Define área onde o fundo é aplicado.","background-clip: border-box;","Cores e Background","css"),
    ("background-blend-mode","Define modo de mistura entre fundos.","background-blend-mode: multiply;","Cores e Background","css"),
    ("linear-gradient","Define gradiente linear como imagem de fundo.","background-image: linear-gradient(to right, red, blue);","Cores e Background","css"),
    ("radial-gradient","Define gradiente radial como imagem de fundo.","background-image: radial-gradient(circle, red, blue);","Cores e Background","css"),
    ("conic-gradient","Define gradiente cônico como imagem de fundo.","background-image: conic-gradient(red, blue);","Cores e Background","css"),
    ("repeating-linear-gradient","Define gradiente linear repetido.","background-image: repeating-linear-gradient(red 0 10px, blue 10px 20px);","Cores e Background","css"),
    ("repeating-radial-gradient","Define gradiente radial repetido.","background-image: repeating-radial-gradient(red 0 10px, blue 10px 20px);","Cores e Background","css"),
    ("repeating-conic-gradient","Define gradiente cônico repetido.","background-image: repeating-conic-gradient(red 0 10deg, blue 10deg 20deg);","Cores e Background","css"),
    ("mask","Shorthand para propriedades de máscara.","mask: url(mask.png);","Cores e Background","css"),
    ("mask-image","Define imagem de máscara.","mask-image: url(mask.png);","Cores e Background","css"),
    ("mask-mode","Define modo da máscara.","mask-mode: alpha;","Cores e Background","css"),
    ("mask-position","Define posição da máscara.","mask-position: center;","Cores e Background","css"),
    ("mask-size","Define tamanho da máscara.","mask-size: cover;","Cores e Background","css"),
    ("mask-repeat","Define repetição da máscara.","mask-repeat: no-repeat;","Cores e Background","css"),
    ("mask-origin","Define origem da máscara.","mask-origin: padding-box;","Cores e Background","css"),
    ("mask-clip","Define área de aplicação da máscara.","mask-clip: border-box;","Cores e Background","css"),
    ("mask-composite","Define modo de composição da máscara.","mask-composite: add;","Cores e Background","css"),
    ("mix-blend-mode","Define como o elemento se mistura com o fundo.","mix-blend-mode: multiply;","Cores e Background","css"),
    ("isolation","Define se o elemento cria novo contexto de mistura.","isolation: isolate;","Cores e Background","css"),
    ("background-position-x","Define posição horizontal do fundo.","background-position-x: 50%;","Cores e Background","css"),
    ("background-position-y","Define posição vertical do fundo.","background-position-y: 50%;","Cores e Background","css"),
    ("mask-type","Define tipo de máscara (alpha ou luminance).","mask-type: alpha;","Cores e Background","css"),
    ("-webkit-mask","Shorthand da máscara para WebKit.","-webkit-mask: url(mask.png);","Cores e Background","css"),
    ("-webkit-mask-image","Define imagem de máscara no WebKit.","-webkit-mask-image: url(mask.png);","Cores e Background","css"),
    ("-webkit-mask-size","Define tamanho da máscara no WebKit.","-webkit-mask-size: cover;","Cores e Background","css"),
    ("-webkit-mask-position","Define posição da máscara no WebKit.","-webkit-mask-position: center;","Cores e Background","css"),
    ("-webkit-mask-repeat","Define repetição da máscara no WebKit.","-webkit-mask-repeat: no-repeat;","Cores e Background","css"),
    ("-webkit-mask-clip","Define área de aplicação da máscara no WebKit.","-webkit-mask-clip: border-box;","Cores e Background","css"),
    ("-webkit-mask-origin","Define origem da máscara no WebKit.","-webkit-mask-origin: padding-box;","Cores e Background","css"),
    ("-webkit-mask-composite","Define composição da máscara no WebKit.","-webkit-mask-composite: source-over;","Cores e Background","css"),
    ('border-image', 'Usa uma imagem como borda do elemento.', 'div { border-image: url(border.png) 30 stretch; }', 'Cores e Background', 'css'),
    ('border-image-slice', 'Define como a imagem da borda será cortada.', 'div { border-image-slice: 30; }', 'Cores e Background', 'css'),
    ('border-image-repeat', 'Define como a imagem da borda será repetida.', 'div { border-image-repeat: round; }', 'Cores e Background', 'css'),
    ('outline', 'Desenha contorno em volta do elemento.', 'input:focus { outline: 2px solid blue; }', 'Cores e Background', 'css'),
    ('outline-offset', 'Define a distância entre o contorno e a borda.', 'input:focus { outline-offset: 4px; }', 'Cores e Background', 'css'),
    ('clip-path', 'Recorta o elemento em uma forma definida.', "div { clip-path: circle(50% at 50% 50%); }", 'Cores e Background', 'css'),

    # --- Flexbox ---

    ("display","Define o elemento como container flex.","display: flex;","Flexbox","css"),
    ("flex-direction","Define direção dos itens flex.","flex-direction: row;","Flexbox","css"),
    ("flex-wrap","Define se os itens podem quebrar linha.","flex-wrap: wrap;","Flexbox","css"),
    ("flex-flow","Shorthand para flex-direction e flex-wrap.","flex-flow: row wrap;","Flexbox","css"),
    ("justify-content","Alinha itens no eixo principal.","justify-content: center;","Flexbox","css"),
    ("align-items","Alinha itens no eixo transversal.","align-items: center;","Flexbox","css"),
    ("align-content","Alinha múltiplas linhas no eixo transversal.","align-content: space-between;","Flexbox","css"),
    ("gap","Define espaçamento entre itens flex.","gap: 20px;","Flexbox","css"),
    ("row-gap","Define espaçamento entre linhas.","row-gap: 10px;","Flexbox","css"),
    ("column-gap","Define espaçamento entre colunas.","column-gap: 20px;","Flexbox","css"),
    ("order","Define ordem do item flex.","order: 2;","Flexbox","css"),
    ("flex-grow","Define quanto o item pode crescer.","flex-grow: 1;","Flexbox","css"),
    ("flex-shrink","Define quanto o item pode encolher.","flex-shrink: 1;","Flexbox","css"),
    ("flex-basis","Define tamanho inicial do item.","flex-basis: 200px;","Flexbox","css"),
    ("flex","Shorthand para flex-grow, flex-shrink e flex-basis.","flex: 1 1 auto;","Flexbox","css"),
    ("align-self","Alinha item individual no eixo transversal.","align-self: center;","Flexbox","css"),
    ("place-content","Shorthand para align-content e justify-content.","place-content: center;","Flexbox","css"),
    ("place-items","Shorthand para align-items e justify-items.","place-items: center;","Flexbox","css"),
    ("place-self","Shorthand para align-self e justify-self.","place-self: center;","Flexbox","css"),
    ('order', 'Define a ordem do item flex dentro do container.', 'div { order: 2; }', 'Flexbox', 'css'),
    ('align-self', 'Alinha individualmente um item no container flex/grid.', 'div { align-self: flex-end; }', 'Flexbox', 'css'),

    # --- Grid ---

    ("display","Define o elemento como container grid.","display: grid;","Grid","css"),
    ("grid-template-columns","Define as colunas do grid.","grid-template-columns: 1fr 1fr;","Grid","css"),
    ("grid-template-rows","Define as linhas do grid.","grid-template-rows: auto 200px;","Grid","css"),
    ("grid-template-areas","Define áreas nomeadas no grid.","grid-template-areas: 'header header' 'main aside';","Grid","css"),
    ("grid-template","Shorthand para template de linhas, colunas e áreas.","grid-template: auto / 1fr 1fr;","Grid","css"),
    ("grid-auto-columns","Define tamanho de colunas automáticas.","grid-auto-columns: 200px;","Grid","css"),
    ("grid-auto-rows","Define tamanho de linhas automáticas.","grid-auto-rows: 100px;","Grid","css"),
    ("grid-auto-flow","Define fluxo automático do grid.","grid-auto-flow: row;","Grid","css"),
    ("gap","Define espaçamento entre células.","gap: 20px;","Grid","css"),
    ("row-gap","Define espaçamento entre linhas.","row-gap: 10px;","Grid","css"),
    ("column-gap","Define espaçamento entre colunas.","column-gap: 20px;","Grid","css"),
    ("justify-items","Alinha itens no eixo inline.","justify-items: center;","Grid","css"),
    ("align-items","Alinha itens no eixo block.","align-items: center;","Grid","css"),
    ("place-items","Shorthand para justify-items e align-items.","place-items: center;","Grid","css"),
    ("justify-content","Alinha o grid inteiro no eixo inline.","justify-content: center;","Grid","css"),
    ("align-content","Alinha o grid inteiro no eixo block.","align-content: center;","Grid","css"),
    ("place-content","Shorthand para justify-content e align-content.","place-content: center;","Grid","css"),
    ("grid-column-start","Define início da coluna do item.","grid-column-start: 1;","Grid","css"),
    ("grid-column-end","Define fim da coluna do item.","grid-column-end: 3;","Grid","css"),
    ("grid-row-start","Define início da linha do item.","grid-row-start: 1;","Grid","css"),
    ("grid-row-end","Define fim da linha do item.","grid-row-end: 2;","Grid","css"),
    ("grid-column","Shorthand para column-start e column-end.","grid-column: 1 / 3;","Grid","css"),
    ("grid-row","Shorthand para row-start e row-end.","grid-row: 1 / 2;","Grid","css"),
    ("grid-area","Define área nomeada ou posição do item.","grid-area: header;","Grid","css"),
    ("justify-self","Alinha item individual no eixo inline.","justify-self: center;","Grid","css"),
    ("align-self","Alinha item individual no eixo block.","align-self: center;","Grid","css"),
    ("place-self","Shorthand para justify-self e align-self.","place-self: center;","Grid","css"),
    ("subgrid","Permite herdar definição de linhas/colunas do grid pai.","grid-template-columns: subgrid;","Grid","css"),
    ('grid-area', 'Define a área ocupada pelo item no grid.', 'div { grid-area: header; }', 'Grid', 'css'),
    ('grid-template-areas', 'Define áreas nomeadas do grid para posicionamento.', 'grid-template-areas: "header header" "sidebar main";', 'Grid', 'css'),

    # --- Efeitos Visuais ---

    ("box-shadow","Adiciona sombra ao elemento.","box-shadow: 2px 2px 10px rgba(0,0,0,0.3);","Efeitos Visuais","css"),
    ("text-shadow","Adiciona sombra ao texto.","text-shadow: 1px 1px 4px black;","Efeitos Visuais","css"),
    ("opacity","Define o nível de transparência do elemento.","opacity: 0.7;","Efeitos Visuais","css"),
    ("visibility","Controla se o elemento é visível ou oculto.","visibility: hidden;","Efeitos Visuais","css"),
    ("filter","Aplica efeitos gráficos como blur, contraste e brilho.","filter: blur(5px);","Efeitos Visuais","css"),
    ("backdrop-filter","Aplica efeitos ao fundo atrás do elemento.","backdrop-filter: blur(10px);","Efeitos Visuais","css"),
    ("mix-blend-mode","Define como o elemento se mistura com o fundo.","mix-blend-mode: multiply;","Efeitos Visuais","css"),
    ("background-blend-mode","Define mistura entre camadas de fundo.","background-blend-mode: overlay;","Efeitos Visuais","css"),
    ("isolation","Cria novo contexto de empilhamento para mistura.","isolation: isolate;","Efeitos Visuais","css"),
    ("clip-path","Define recorte moderno do elemento.","clip-path: circle(50%);","Efeitos Visuais","css"),
    ("clip","Define recorte antigo (obsoleto).","clip: rect(0,50px,50px,0);","Efeitos Visuais","css"),
    ("mask","Shorthand para propriedades de máscara.","mask: url(mask.png);","Efeitos Visuais","css"),
    ("mask-image","Define imagem de máscara.","mask-image: url(mask.png);","Efeitos Visuais","css"),
    ("mask-mode","Define modo da máscara.","mask-mode: alpha;","Efeitos Visuais","css"),
    ("mask-position","Define posição da máscara.","mask-position: center;","Efeitos Visuais","css"),
    ("mask-size","Define tamanho da máscara.","mask-size: cover;","Efeitos Visuais","css"),
    ("mask-repeat","Define repetição da máscara.","mask-repeat: no-repeat;","Efeitos Visuais","css"),
    ("mask-origin","Define origem da máscara.","mask-origin: padding-box;","Efeitos Visuais","css"),
    ("mask-clip","Define área onde máscara é aplicada.","mask-clip: border-box;","Efeitos Visuais","css"),
    ("mask-composite","Define composição da máscara.","mask-composite: add;","Efeitos Visuais","css"),
    ("mask-type","Define tipo da máscara (alpha/luminance).","mask-type: alpha;","Efeitos Visuais","css"),
    ("-webkit-mask-image","Versão WebKit de mask-image.","-webkit-mask-image: url(mask.png);","Efeitos Visuais","css"),
    ("-webkit-mask-size","Versão WebKit de mask-size.","-webkit-mask-size: cover;","Efeitos Visuais","css"),
    ("-webkit-mask-position","Versão WebKit de mask-position.","-webkit-mask-position: center;","Efeitos Visuais","css"),
    ("-webkit-mask-repeat","Versão WebKit de mask-repeat.","-webkit-mask-repeat: no-repeat;","Efeitos Visuais","css"),
    ("-webkit-mask-clip","Versão WebKit de mask-clip.","-webkit-mask-clip: border-box;","Efeitos Visuais","css"),
    ("-webkit-mask-origin","Versão WebKit de mask-origin.","-webkit-mask-origin: padding-box;","Efeitos Visuais","css"),
    ("-webkit-mask-composite","Versão WebKit de mask-composite.","-webkit-mask-composite: source-over;","Efeitos Visuais","css"),
    ("outline","Define contorno externo ao elemento.","outline: 2px solid red;","Efeitos Visuais","css"),
    ("outline-offset","Define distância do outline.","outline-offset: 4px;","Efeitos Visuais","css"),
    ("image-rendering","Define algoritmo de renderização da imagem.","image-rendering: crisp-edges;","Efeitos Visuais","css"),
    ("object-fit","Define como conteúdo se ajusta ao container.","object-fit: cover;","Efeitos Visuais","css"),
    ("object-position","Define posição do objeto no container.","object-position: center;","Efeitos Visuais","css"),
    ("caret-color","Define a cor do cursor de texto.","caret-color: red;","Efeitos Visuais","css"),
    ('mix-blend-mode', 'Define como o conteúdo se mistura com o background.', 'div { mix-blend-mode: multiply; }', 'Efeitos Visuais', 'css'),
    ('isolation', 'Controla o isolamento de blending do elemento.', 'div { isolation: isolate; }', 'Efeitos Visuais', 'css'),
    ('will-change', 'Informa ao navegador que propriedades podem mudar, otimizando performance.', 'div { will-change: transform; }', 'Efeitos Visuais', 'css'),
    ('scroll-behavior', 'Define o comportamento de rolagem suave ou instantânea.', 'html { scroll-behavior: smooth; }', 'Efeitos Visuais', 'css'),
    ('scroll-snap-type', 'Define pontos de “snap” ao rolar em containers.', 'div { scroll-snap-type: x mandatory; }', 'Efeitos Visuais', 'css'),
    ('scroll-snap-align', 'Alinha elementos nos pontos de snap.', 'div { scroll-snap-align: start; }', 'Efeitos Visuais', 'css'),

    # --- Transformações ---

    ("transform","Aplica transformações 2D ou 3D ao elemento.","transform: rotate(45deg);","Transformações","css"),
    ("transform-origin","Define o ponto de origem da transformação.","transform-origin: center;","Transformações","css"),
    ("transform-style","Define se os filhos preservam o espaço 3D.","transform-style: preserve-3d;","Transformações","css"),
    ("translate","Define deslocamento individual.","translate: 10px 20px;","Transformações","css"),
    ("rotate","Define rotação individual.","rotate: 45deg;","Transformações","css"),
    ("scale","Define escala individual.","scale: 1.2;","Transformações","css"),
    ("translateX","Move no eixo X.","transform: translateX(20px);","Transformações","css"),
    ("translateY","Move no eixo Y.","transform: translateY(20px);","Transformações","css"),
    ("translateZ","Move no eixo Z.","transform: translateZ(100px);","Transformações","css"),
    ("translate3d","Move nos eixos X, Y e Z.","transform: translate3d(10px,20px,50px);","Transformações","css"),
    ("scaleX","Redimensiona no eixo X.","transform: scaleX(1.5);","Transformações","css"),
    ("scaleY","Redimensiona no eixo Y.","transform: scaleY(1.5);","Transformações","css"),
    ("scaleZ","Redimensiona no eixo Z.","transform: scaleZ(1.5);","Transformações","css"),
    ("scale3d","Redimensiona nos três eixos.","transform: scale3d(1.2,1.2,1.2);","Transformações","css"),
    ("rotateX","Rotaciona no eixo X.","transform: rotateX(45deg);","Transformações","css"),
    ("rotateY","Rotaciona no eixo Y.","transform: rotateY(45deg);","Transformações","css"),
    ("rotateZ","Rotaciona no eixo Z.","transform: rotateZ(45deg);","Transformações","css"),
    ("rotate3d","Rotaciona em vetor 3D personalizado.","transform: rotate3d(1,1,0,45deg);","Transformações","css"),
    ("skew","Inclina nos eixos X e Y.","transform: skew(10deg,10deg);","Transformações","css"),
    ("skewX","Inclina no eixo X.","transform: skewX(10deg);","Transformações","css"),
    ("skewY","Inclina no eixo Y.","transform: skewY(10deg);","Transformações","css"),
    ("matrix","Define transformação 2D via matriz.","transform: matrix(1,0,0,1,0,0);","Transformações","css"),
    ("matrix3d","Define transformação 3D via matriz 4x4.","transform: matrix3d(...);","Transformações","css"),

    # --- Responsividade ---

    ("@media","Aplica estilos condicionalmente com base em condições.","@media (max-width: 768px) { ... }","Responsividade","css"),
    ("@supports","Aplica estilos se o navegador suportar determinada regra.","@supports (display: grid) { ... }","Responsividade","css"),
    ("@container","Aplica estilos com base no tamanho do container.","@container (min-width: 400px) { ... }","Responsividade","css"),
    ("container-type","Define o tipo de container para consultas.","container-type: inline-size;","Responsividade","css"),
    ("container-name","Define nome do container.","container-name: card;","Responsividade","css"),
    ("container","Shorthand para container-name e container-type.","container: card / inline-size;","Responsividade","css"),
    ("vw","Unidade baseada na largura da viewport.","width: 50vw;","Responsividade","css"),
    ("vh","Unidade baseada na altura da viewport.","height: 100vh;","Responsividade","css"),
    ("vmin","Baseado no menor valor entre largura e altura.","width: 50vmin;","Responsividade","css"),
    ("vmax","Baseado no maior valor entre largura e altura.","width: 50vmax;","Responsividade","css"),
    ("svh","Viewport pequeno (mobile UI dinâmica).","height: 100svh;","Responsividade","css"),
    ("lvh","Viewport grande.","height: 100lvh;","Responsividade","css"),
    ("dvh","Viewport dinâmica.","height: 100dvh;","Responsividade","css"),
    ("svw","Viewport pequeno largura.","width: 100svw;","Responsividade","css"),
    ("lvw","Viewport grande largura.","width: 100lvw;","Responsividade","css"),
    ("dvw","Viewport dinâmica largura.","width: 100dvw;","Responsividade","css"),
    ("min","Retorna o menor valor.","width: min(100%, 600px);","Responsividade","css"),
    ("max","Retorna o maior valor.","width: max(300px, 50%);","Responsividade","css"),
    ("clamp","Define valor fluido com limites.","font-size: clamp(1rem, 2vw, 2rem);","Responsividade","css"),
    ("aspect-ratio","Define proporção automática do elemento.","aspect-ratio: 16 / 9;","Responsividade","css"),
    ("width","Largura da viewport em media query.","@media (max-width: 768px) { ... }","Responsividade","css"),
    ("height","Altura da viewport em media query.","@media (max-height: 600px) { ... }","Responsividade","css"),
    ("orientation","Detecta orientação da tela.","@media (orientation: landscape) { ... }","Responsividade","css"),
    ("aspect-ratio","Detecta proporção da tela.","@media (aspect-ratio: 16/9) { ... }","Responsividade","css"),
    ("hover","Detecta suporte a hover.","@media (hover: hover) { ... }","Responsividade","css"),
    ("pointer","Detecta tipo de ponteiro.","@media (pointer: coarse) { ... }","Responsividade","css"),
    ("prefers-color-scheme","Detecta modo claro/escuro.","@media (prefers-color-scheme: dark) { ... }","Responsividade","css"),
    ("prefers-reduced-motion","Detecta preferência por menos animação.","@media (prefers-reduced-motion: reduce) { ... }","Responsividade","css"),
    ("prefers-contrast","Detecta preferência de contraste.","@media (prefers-contrast: more) { ... }","Responsividade","css"),
    ("rem","Unidade relativa à raiz do documento.","font-size: 1.2rem;","Responsividade","css"),
    ("em","Unidade relativa ao elemento pai.","font-size: 1.2em;","Responsividade","css"),
    ("%","Valor relativo ao elemento pai.","width: 100%;","Responsividade","css"),

    # --- Variáveis CSS ---

    ("--cor-primaria","Define uma variável CSS customizada.","--cor-primaria: blue;","Variáveis CSS","css"),
    ("var()","Utiliza uma variável CSS.","color: var(--cor-primaria);","Variáveis CSS","css"),
    (":root","Define variáveis globais.",":root { --cor-primaria: blue; }","Variáveis CSS","css"),
    ("Escopo local","Define variável apenas dentro de um seletor.","div { --cor-primaria: green; }","Variáveis CSS","css"),
    ("Variável em cálculo","Usa variável dentro de funções CSS.","width: calc(var(--largura) * 2);","Variáveis CSS","css"),
    ("setProperty()","Altera variável via JavaScript.","element.style.setProperty('--cor-primaria','red');","Variáveis CSS","css"),
    ("@property","Define tipagem e comportamento de uma variável CSS.","@property --cor-primaria { syntax: '<color>'; inherits: false; initial-value: blue; }","Variáveis CSS","css"),

    # --- Pseudo-classes ---

    (':hover', 'Aplica estilo quando o usuário posiciona o cursor sobre o elemento.', 'elemento:hover { color: red; }', 'Pseudo-classes', 'css'),
    (':active', 'Aplica estilo enquanto o elemento está sendo ativado/clicado.', 'elemento:active { background: yellow; }', 'Pseudo-classes', 'css'),
    (':focus', 'Aplica estilo quando o elemento recebe foco (input, textarea, botão).', 'elemento:focus { outline: 2px solid blue; }', 'Pseudo-classes', 'css'),
    (':visited', 'Aplica estilo a links que já foram visitados.', 'a:visited { color: purple; }', 'Pseudo-classes', 'css'),
    (':link', 'Aplica estilo a links ainda não visitados.', 'a:link { color: blue; }', 'Pseudo-classes', 'css'),
    (':first-child', 'Aplica estilo ao primeiro filho de um elemento pai.', 'p:first-child { font-weight: bold; }', 'Pseudo-classes', 'css'),
    (':last-child', 'Aplica estilo ao último filho de um elemento pai.', 'p:last-child { font-style: italic; }', 'Pseudo-classes', 'css'),
    (':nth-child(n)', 'Aplica estilo ao n-ésimo filho de um elemento pai.', 'li:nth-child(2) { color: green; }', 'Pseudo-classes', 'css'),
    (':nth-last-child(n)', 'Aplica estilo ao n-ésimo filho a partir do final.', 'li:nth-last-child(1) { font-size: 20px; }', 'Pseudo-classes', 'css'),
    (':first-of-type', 'Aplica estilo ao primeiro filho do tipo específico.', 'p:first-of-type { text-decoration: underline; }', 'Pseudo-classes', 'css'),
    (':last-of-type', 'Aplica estilo ao último filho do tipo específico.', 'p:last-of-type { color: orange; }', 'Pseudo-classes', 'css'),
    (':nth-of-type(n)', 'Aplica estilo ao n-ésimo filho do tipo específico.', 'p:nth-of-type(3) { font-weight: bold; }', 'Pseudo-classes', 'css'),
    (':nth-last-of-type(n)', 'Aplica estilo ao n-ésimo filho do tipo específico a partir do final.', 'p:nth-last-of-type(2) { font-style: italic; }', 'Pseudo-classes', 'css'),
    (':only-child', 'Aplica estilo se o elemento é o único filho de seu pai.', 'p:only-child { border: 1px solid red; }', 'Pseudo-classes', 'css'),
    (':only-of-type', 'Aplica estilo se o elemento é o único de seu tipo entre os irmãos.', 'p:only-of-type { background: yellow; }', 'Pseudo-classes', 'css'),
    (':empty', 'Aplica estilo se o elemento não possui filhos nem texto.', 'div:empty { display: none; }', 'Pseudo-classes', 'css'),
    (':not(selector)', 'Aplica estilo a elementos que não correspondem ao seletor.', 'p:not(.ativo) { opacity: 0.5; }', 'Pseudo-classes', 'css'),
    (':enabled', 'Aplica estilo a elementos habilitados.', 'input:enabled { background: white; }', 'Pseudo-classes', 'css'),
    (':disabled', 'Aplica estilo a elementos desabilitados.', 'input:disabled { background: gray; }', 'Pseudo-classes', 'css'),
    (':checked', 'Aplica estilo a inputs tipo radio ou checkbox marcados.', 'input:checked { accent-color: green; }', 'Pseudo-classes', 'css'),
    (':default', 'Aplica estilo ao elemento de formulário padrão.', 'input:default { border-color: blue; }', 'Pseudo-classes', 'css'),
    (':required', 'Aplica estilo a campos de formulário obrigatórios.', 'input:required { border: 2px solid red; }', 'Pseudo-classes', 'css'),
    (':optional', 'Aplica estilo a campos de formulário opcionais.', 'input:optional { border: 2px dashed gray; }', 'Pseudo-classes', 'css'),
    (':valid', 'Aplica estilo a campos de formulário válidos.', 'input:valid { background: lightgreen; }', 'Pseudo-classes', 'css'),
    (':invalid', 'Aplica estilo a campos de formulário inválidos.', 'input:invalid { background: lightcoral; }', 'Pseudo-classes', 'css'),
    (':in-range', 'Aplica estilo a campos numéricos dentro do range definido.', 'input:in-range { border-color: green; }', 'Pseudo-classes', 'css'),
    (':out-of-range', 'Aplica estilo a campos numéricos fora do range definido.', 'input:out-of-range { border-color: red; }', 'Pseudo-classes', 'css'),
    (':read-only', 'Aplica estilo a campos somente leitura.', 'input:read-only { background: #f0f0f0; }', 'Pseudo-classes', 'css'),
    (':read-write', 'Aplica estilo a campos editáveis.', 'input:read-write { background: white; }', 'Pseudo-classes', 'css'),
    (':focus-within', 'Aplica estilo a elementos que possuem foco em um de seus descendentes.', 'div:focus-within { border: 2px solid blue; }', 'Pseudo-classes', 'css'),
    (':focus-visible', 'Aplica estilo quando o elemento recebe foco visível (usado para acessibilidade).', 'button:focus-visible { outline: 2px solid orange; }', 'Pseudo-classes', 'css'),
    (':hover, :focus', 'Aplica estilo ao elemento quando está hover ou focus.', 'elemento:hover, elemento:focus { color: red; }', 'Pseudo-classes', 'css'),
    (':any-link', 'Aplica estilo a qualquer link, visitado ou não.', 'a:any-link { color: teal; }', 'Pseudo-classes', 'css'),
    (':is(selector)', 'Aplica estilo se o elemento corresponde a qualquer um dos seletores listados.', 'p:is(.ativo, .destaque) { font-weight: bold; }', 'Pseudo-classes', 'css'),
    (':where(selector)', 'Aplica estilo a elementos correspondentes a seletores sem aumentar a especificidade.', 'div:where(.card, .alert) { margin: 10px; }', 'Pseudo-classes', 'css'),
    (':has(selector)', 'Aplica estilo a elementos que possuem descendentes correspondentes ao seletor.', 'div:has(p.ativo) { border: 2px solid red; }', 'Pseudo-classes', 'css'),
    (':target', 'Aplica estilo ao elemento que corresponde à âncora da URL atual.', '#secao1:target { background: yellow; }', 'Pseudo-classes', 'css'),
    (':lang(código-língua)', 'Aplica estilo a elementos de acordo com o idioma definido.', 'p:lang(en) { font-style: italic; }', 'Pseudo-classes', 'css'),
    (':placeholder-shown', 'Aplica estilo quando o placeholder está visível.', 'input:placeholder-shown { color: gray; }', 'Pseudo-classes', 'css'),
    (':indeterminate', 'Aplica estilo quando um checkbox está indeterminado.', 'input:indeterminate { background-color: orange; }', 'Pseudo-classes', 'css'),
    (':-webkit-autofill', 'Aplica estilo a campos preenchidos automaticamente pelo navegador.', 'input:-webkit-autofill { background-color: lightyellow; }', 'Pseudo-classes', 'css'),

    # --- Pseudo-elementos ---

    ('::after','Insere conteúdo após o conteúdo real do elemento.','p::after { content: "→"; color: red; }','Pseudo-elementos','css'),
    ('::before','Insere conteúdo antes do conteúdo real do elemento.','p::before { content: "←"; color: blue; }','Pseudo-elementos','css'),
    ('::first-letter','Aplica estilo à primeira letra do elemento.','p::first-letter { font-size: 2em; font-weight: bold; }','Pseudo-elementos','css'),
    ('::first-line','Aplica estilo à primeira linha do elemento.','p::first-line { font-variant: small-caps; }','Pseudo-elementos','css'),
    ('::selection','Aplica estilo ao texto selecionado pelo usuário.','p::selection { background: yellow; color: black; }','Pseudo-elementos','css'),
    ('::placeholder','Aplica estilo ao texto placeholder de inputs.','input::placeholder { color: gray; font-style: italic; }','Pseudo-elementos','css'),
    ('::backdrop','Aplica estilo ao fundo de elementos <dialog> abertos.','dialog::backdrop { background: rgba(0,0,0,0.5); }','Pseudo-elementos','css'),
    ('::marker','Aplica estilo aos marcadores de listas (<li>).','li::marker { color: red; font-size: 1.2em; }','Pseudo-elementos','css'),
    ('::spelling-error','Aplica estilo a palavras com erro ortográfico detectadas pelo navegador.','span::spelling-error { text-decoration: underline wavy red; }','Pseudo-elementos','css'),
    ('::grammar-error','Aplica estilo a erros gramaticais detectados pelo navegador.','span::grammar-error { text-decoration: underline wavy orange; }','Pseudo-elementos','css'),
    ('::file-selector-button','Aplica estilo ao botão de input[type="file"].','input[type="file"]::file-selector-button { background: blue; color: white; }','Pseudo-elementos','css'),
    ('::cue','Aplica estilo a legendas de vídeos (<track>), usado em mídia.','::cue { color: yellow; background: black; }','Pseudo-elementos','css'),
    ('::part','Permite estilizar partes de um Web Component expostas via part.','my-element::part(button) { color: red; }','Pseudo-elementos','css'),
    ('::slotted','Aplica estilo ao conteúdo passado para slots de Web Components.','slot::slotted(p) { color: green; }','Pseudo-elementos','css'),

    # --- Outros ---

    ('cursor', 'Define o tipo de cursor quando passa sobre o elemento.', 'button { cursor: pointer; }', 'Interatividade', 'css'),
    ('resize', 'Permite que o elemento seja redimensionável.', 'textarea { resize: both; }', 'Interatividade', 'css'),
    ('overflow', 'Controla o que acontece quando o conteúdo excede a área.', 'div { overflow: auto; }', 'Layout e Posicionamento', 'css'),
    ('overflow-x', 'Controla o overflow horizontal.', 'div { overflow-x: scroll; }', 'Layout e Posicionamento', 'css'),
    ('overflow-y', 'Controla o overflow vertical.', 'div { overflow-y: hidden; }', 'Layout e Posicionamento', 'css'),

]   
class Command(BaseCommand):
    help = 'Deu errado kkkk'
    def handle(self, *args, **kwargs): 
        for nome, descricao, uso, nome_categoria, linguagem in codigos:
            categoria = Categoria.objects.get(
                nome=nome_categoria,
                linguagem=linguagem
            )
            Codigo.objects.get_or_create(
                nome=nome,
                categoria=categoria,
                defaults={
                    'descricao': descricao,
                    'modoDeUsar': uso
                })
        self.stdout.write(self.style.SUCCESS('Dados registrados!'))