# Generated by Django 4.2.28 on 2026-02-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=300)),
                ('modoDeUsar', models.TextField(max_length=200)),
                ('linguagem', models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript')], max_length=30)),
            ],
        ),
    ]
