# Generated by Django 4.2.28 on 2026-02-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
