# Generated by Django 4.2.28 on 2026-02-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='codigo',
            name='modoDeUsar',
            field=models.TextField(),
        ),
    ]
