# Generated by Django 4.2.28 on 2026-02-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_codigo_descricao_alter_codigo_mododeusar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='linguagem',
            field=models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('js', 'JS')], max_length=30),
        ),
    ]
